workflows:
  native-android:
    name: Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    scripts:
      - name: Set Android SDK location
        script: |
          echo "hello world"
